[JamManSettings]
#JamManStereo or JamManSoloXT
JamManType=JamManSoloXT
# Volume Name your SSD drive
SSDLocation=JAMMAN
# Change the below to your own location of where you want to store all your wav files.
wavFileLoc=C:\Users\RayBe\OneDrive\Documents\jammangolang\music

[PhraseXMLDefaults]
# Default beats per minute for phrase XML
BeatsPerMinute=124.9213180542
# Default beats per measure for phrase XML
BeatsPerMeasure=4
# Default loop setting for phrase XML (0 or 1)
IsLoop=1